# Generated by Django 3.1.4 on 2020-12-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20)),
                ('test_name2', models.CharField(max_length=10)),
                ('test_num', models.CharField(max_length=20)),
                ('test_addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.CharField(max_length=3)),
                ('item_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.test1')),
            ],
        ),
    ]
